In [8]:
import pandas as pd

# Step 1: Read the binary parquet file created by our pipeline
saved_cohort_data = pd.read_parquet("../data/extract_patient_cohort.parquet")

# Step 2: Print out the internal properties of our data frame for verification
print(f"Total Rows Extracted: {len(saved_cohort_data)}")
print(f"Data Columns Present: {list(saved_cohort_data.columns)}")

# Step 3: Render the clear dataframe spreadsheet directly inside the notebook window
saved_cohort_data.head(10)

Total Rows Extracted: 364627
Data Columns Present: ['subject_id', 'gender', 'anchor_age', 'anchor_year', 'dod']

   subject_id gender  anchor_age  anchor_year         dod
0    10000032      F          52         2180  2180-09-09
1    10000048      F          23         2126         NaN
2    10000058      F          33         2168         NaN
3    10000068      F          19         2160         NaN
4    10000084      M          72         2160  2161-02-13
5    10000102      F          27         2136         NaN
6    10000108      M          25         2163         NaN
7    10000115      M          24         2154         NaN
8    10000117      F          48         2174         NaN
9    10000161      M          60         2163         NaN

In [7]:
import pandas as pd

# 1. Read the newly generated diagnosis cohort file
diabetes_cohort = pd.read_parquet("../data/diabetes_cohort_list.parquet")

# 2. Display basic dimensions (Rows and Columns)
print("STUDY COHORT DIMENSIONS ")
print(f"Total Rows (Patients): {diabetes_cohort.shape[0]:,}")
print(f"Total Columns: {diabetes_cohort.shape[1]}")
print(f"Column Names: {list(diabetes_cohort.columns)}")

# 3. Render the first few rows as an interactive visual table
print("First 5 rows of diabetes cohort:")
diabetes_cohort.head(5)

STUDY COHORT DIMENSIONS
Total Rows (Patients): 100,585
Total Columns: 4
Column Names: ['subject_id', 'hadm_id', 'icd_code', 'icd_version']
First 5 rows of diabetes cohort:

   subject_id   hadm_id icd_code  icd_version
0    10000635  20642640     E119           10
1    10000635  26134563    25000            9
2    10000980  20897796    E1122           10
3    10000980  24947999    25000            9
4    10000980  25911675     E118           10